name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          cd ~/Development/jobhuntbot
          git pull origin main
          source venv/bin/activate
	  pkill -f job_hunt_bot.py || true
          nohup python job_hunt_bot.py > output.log 2>&1 &

