name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.1.224
          username: taylor
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Development/jobhuntbot
            git pull origin main
            source venv/bin/activate
            nohup python job_hunt_bot.py > output.log 2>&1 &

